### ISSUE TITLE
Blur written cards for other participants until opened by author, timeout or a moderator

### ISSUE THREAD

**Issue by AndreasUfert** [antoinejaussoin/retro-board#100]
In a retro, participants shouldn't influence each other's reflections while writing cards on the retro board. So it would be nice if all cards were blurred for other users initially.

Un-blurring could be triggered by either
- the author
- a moderator (session-opener?)
- a timeout (set by moderator)

**Comment by antoinejaussoin** [comment]
That's actually an excellent idea, I love it. I'll try to integrate this on the upcoming v3. thanks!
