### ISSUE TITLE
Kubernetes Backend Pod Fails: Error: secret option required for sessions

### ISSUE THREAD

**Issue by wurst44** [antoinejaussoin/retro-board#101]
Using retro-board-backend:v3, retro-board-frontend:v3 from dockerhub for Docker compose and Kubernetes. 

The **Kubernetes Backend** Pod does not startup corretly:

yarn run v1.22.0
$ yarn migrate && cd ./retro-board-server/dist/src && node index.js
$ cd retro-board-server && yarn migrate && cd ..
$ ts-node ./src/init.ts && ts-node ../node_modules/typeorm/cli.js migration:run
Creating ormconfig.json before migrations
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = current_schema() AND "table_name" = 'migrations'
query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
No migrations are pending
Wed, 08 Apr 2020 05:06:15 GMT express-session deprecated req.secret; provide secret option at index.js:103:50
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
💻  Using Postgres database
Server started on port 3201, environment: production
(node:29) **UnhandledPromiseRejectionWarning: TypeError: OAuthStrategy requires a consumerKey option**
    at Strategy.OAuthStrategy (/usr/src/backend/node_modules/passport-oauth1/lib/strategy.js:83:37)
    at new Strategy (/usr/src/backend/node_modules/passport-twitter/lib/strategy.js:53:17)
    at Object.default (/usr/src/backend/retro-board-server/dist/src/auth/passport.js:87:28)
    at /usr/src/backend/retro-board-server/dist/src/index.js:138:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
**Error: secret option required for sessions**
    at session (/usr/src/backend/node_modules/express-session/index.js:200:12)
    at Layer.handle [as handle_request] (/usr/src/backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/backend/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/backend/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/backend/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/usr/src/backend/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/usr/src/backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/backend/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/backend/node_modules/express/lib/router/index.js:284:7
Error: secret option required for sessions

**Same with Docker compose:**

backend_1   | 💻  Using Postgres database
backend_1   | Server started on port 3201, environment: production
backend_1   | (node:27) UnhandledPromiseRejectionWarning: TypeError: OAuthStrategy requires a consumerKey option
backend_1   |     at Strategy.OAuthStrategy (/usr/src/backend/node_modules/passport-oauth1/lib/strategy.js:83:37)
backend_1   |     at new Strategy (/usr/src/backend/node_modules/passport-twitter/lib/strategy.js:53:17)
backend_1   |     at Object.default (/usr/src/backend/retro-board-server/dist/src/auth/passport.js:87:28)
backend_1   |     at /usr/src/backend/retro-board-server/dist/src/index.js:138:23
backend_1   |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
backend_1   | (node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
backend_1   | (node:27) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
retro-board_frontend_1 exited with code 2

**Comment by wurst44** [comment]
FE/BE latest throws this error: 

$ yarn migrate && cd ./retro-board-server/dist/src && node index.js
$ cd retro-board-server && yarn migrate && cd ..
$ ts-node ./src/init.ts && ts-node ../node_modules/typeorm/cli.js migration:run
Creating ormconfig.json before migrations
error Command failed with signal "SIGKILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by wurst44** [comment]
Sry my bad, it was a problem with the PVC. But in v3 you need to somehow set this?
GIPHY_API_KEY: XXX
SESSION_SECRET: XXX

**Comment by antoinejaussoin** [comment]
Actually the v3 images are not meant to be used, it's still in development. Please use the "latest" ones :)
As for K8s, yes I'll need to add these env variables when I ship the v3.
