### ISSUE TITLE
UI/UX re-design

### ISSUE THREAD

**Issue by mschickensoup** [antoinejaussoin/retro-board#104]
Hello there :-) 

Me and my colleagues from [Polidea](http://www.polidea.com) were talking about the visual look of the retro board. We are super happy to jump in and work on the following aspects:

1. Branding (logotype / colours etc.)
2. User Experience research (user testing, user interviews) + design
3. User Interface design

I have only worked with Apache open source projects, so I'm not really sure how to address it here @antoinejaussoin and if there's room for a discussion for more people on the possible design proposals or it has to be confirmed by you @antoinejaussoin, please let me know. 

There is another project that is worth looking at called [Parabol](https://www.parabol.co/) that I used myself as Project Manager and it was super smooth to carry out the retrospective session with it. That's why, I thought we can make the Retro Board even better looking and more easy-to-use. 

What are your thoughts?

**Comment by mik-laj** [comment]
Thank you very much for supporting this project.😻 This makes me trust this application more because more people will develop it. A strong OOS community is very important.

**Comment by mik-laj** [comment]
@antoinejaussoin What do you think?

**Comment by mik-laj** [comment]
@mschickensoup  I think that we can close this ticket due to the lack of interest in the project maintainer. 😿

**Comment by mschickensoup** [comment]
Yes, I will close it in a sec @mik-laj 😿
