### ISSUE TITLE
Possibility to define sub-location

### ISSUE THREAD

**Issue by ayxos** [antoinejaussoin/retro-board#114]
I have multiple docker containers behind a single Nginx webserver. A sublocation is redirecting to retro-board docker container

```
    location /retro {
        proxy_pass http://127.0.0.1:4000;
    }
```

My problem is all the static files try to fetch from '/' and not from '/retro' I have tried changing BASE_URL on the docker-compose.yml 
```
    BASE_URL: http://my-site.com/retro
```

but it does not work. Any ideas?

**Comment by antoinejaussoin** [comment]
this need to be set up at build time on the frontend, so you'll need to build your own image with the necessary change.
