### ISSUE TITLE
Deleting boards

### ISSUE THREAD

**Issue by edmellum** [antoinejaussoin/retro-board#116]
Deleting boards would be useful for organizing and also important for GDPR compliance. 😄

**Comment by antoinejaussoin** [comment]
This is a very good point, and it's on my short term list of todos. That and a privacy policy, agreement etc...

**Comment by coffeesam** [comment]
👍

**Comment by jghaanstra** [comment]
Yes please ... 

Is there a work-around for now, for instance with a SQL statement over the database?
