### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by ayxos** [antoinejaussoin/retro-board#121]
The following endpoints return an Nginx 504 Gateway Time-out
- /api/custom
- /api/create-custom

 I have tried on different browsers. I am running it via Docker, maybe some base image is failing.

**Comment by michaelpiller** [comment]
I have the same problem.  Any update here?

**Comment by antoinejaussoin** [comment]
These Docker images are running in production right now (on retrospected.com), so they should be working.

**Comment by ayxos** [comment]
I used the docker yml file (develop branch) and a fresh docker environment and was not working. (504 timeout). with a 6 month old docker image was working but the images got updated recently and is no longer working

**Comment by D4rkSh1t** [comment]
I have also the same problem:

If i use the latest docker image in compose file:

  backend:
    image: antoinejaussoin/retro-board-backend:latest
  frontend:
    image: antoinejaussoin/retro-board-frontend:latest

I get this Error:

`frontend_1  | 2020/05/26 07:35:57 [error] 14#14: *2 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.19.0.1, server: localhost, request: "POST /api/create HTTP/1.1", upstream: "http://172.19.0.6:3201/api/create", host: "**", referrer: "http://**/no-referrer"`

After I changed it to:

  backend:
    image: antoinejaussoin/retro-board-backend:3.0.0
  frontend:
    image: antoinejaussoin/retro-board-frontend:3.0.0

Everything works fine.

**Comment by antoinejaussoin** [comment]
Thanks for the update! I will investigate this weekend, and fix it. There must be a problem with the very last image.

**Comment by antoinejaussoin** [comment]
There was indeed an issue with the latest images, if Sentry was not set. I've fixed it, so please pull latest and you should be good to go!
