### ISSUE TITLE
Cant start retrospective

### ISSUE THREAD

**Issue by drm7369** [antoinejaussoin/retro-board#123]
Hey, I think I am encountering a bug.

I clone the current release and use the default compose file, wait 5-10 minutes then browse to localhost:80 or the host VMs IP:80. Im able to create an account and log in but not able to start a retrospective. It lets me mess with the different board options, but wont let me save any as default or start it. Any ideas ? Maybe I am missing something?

`docker-compose -f ./docker-compose.example.yml up -d`

Thanks,

**Comment by antoinejaussoin** [comment]
Hi, there was indeed an issue when running the containers without using Sentry (which is the default). I've fixed it, so you should be able to pull latest and it should now work.
