### ISSUE TITLE
lint -> build

### ISSUE THREAD

**Issue by veselignome** [antoinejaussoin/retro-board#13]
I had lint error when started build/lint tasks. Fixed it by changing lint task in package.json

replaced this
"lint": "eslint --ext .js --ext .jsx ."

with this
"lint": "eslint --ext .js --ext .jsx"

Seems like DOT was the issue (active directory ?)

Just taught I should tell you about this.

Btw, I really like the way you organized code structure.

**Comment by antoinejaussoin** [comment]
Are you using windows ?

**Comment by veselignome** [comment]
No, I'm on linux...
Linux version 3.13.0-77-generic (buildd@lcy01-30) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #121-Ubuntu

**Comment by antoinejaussoin** [comment]
That's odd, i've just run the command on Ubuntu server (where the website is hosted), and it works great. Obviously "." means the current directory, so I wouldn't expect that to be an issue on Linux?

**Comment by antoinejaussoin** [comment]
(tried without the ., doesn't work at all, since eslint expects a directory)

**Comment by antoinejaussoin** [comment]
have you installed the dependencies using `npm i` to be certain that it's going to use the local "eslint" and not a global version you may have?

**Comment by veselignome** [comment]
Yes, I've done git-clone and then npm install to pull all dependencies.
I'll try to find out which lintrc was used on my machine but it's odd to me
as well...

**Comment by antoinejaussoin** [comment]
If you try that from the root of the project, does it work?

`./node_modules/.bin/eslint --ext .js --ext .jsx .`

**Comment by antoinejaussoin** [comment]
(also, what version of Node and NPM do you have?°

**Comment by veselignome** [comment]
I have tried to put ./node_modules and still get the same error. When using ./node_modules and remove active dir (last argument of eslint) it screems like wrong syntax, but when leave out ./node_modules and leave out active dir it works. 

list eslint
retro-board@0.5.1 /home/xxx/test-workspace/retro-board
├── eslint@2.9.0 

npm list eslint -g
/usr/local/lib
└── (empty)

I've pasted error bellow:

npm ERR! Linux 3.13.0-77-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! retro-board@0.5.1 lint: `eslint --ext .js --ext .jsx .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the retro-board@0.5.1 lint script 'eslint --ext .js --ext .jsx .'.

**Comment by veselignome** [comment]
I've found the issue! There was 1 error I missed.

 Unable to resolve path to module './configuration.json'  import/no-unresolved

When I copied configuration_template.json to configuration.json it started to work.

It seems like fileExist in the first line of this code is allways true

const fileExist = fs.existsSync(path.resolve(__dirname, 'configuration.json'));
if (fileExist) {
    module.exports = require('./configuration.json');
} else {
    module.exports = require('./configuration_template.json');
}

so it was allways processing inside if statement requiring file that does not exist.

I'm sorry if I brought confusion,
was just trying to help.

Be well.

**Comment by antoinejaussoin** [comment]
Hi !! It's actually a very good point, I never thought of that: indeed configuration.json is not there by default, but I never tested without it (I always have it). But linting should work without it, since this file is optional. I'll try to figure out a fix :) Thanks for your discovery

**Comment by veselignome** [comment]
It's not much of discovery, but yeah, it's kind of annoying when you download and install package and it's not working, especially if error is not blocking some core features, and I taught I should shout so that others could try it out without debugging.

I think lint breaks because require returns error or something like that.

Cheers ;)

**Comment by antoinejaussoin** [comment]
It's actually quite a big issue: my first goal was to be able to `npm i`then `npm build`and it would work without fiddling with anything else.
That's why I made mongodb optional for instance.
So this is quite a problem, and i'm fixing that right away

**Comment by antoinejaussoin** [comment]
Problem fixed, in master, new version is 0.5.3.
I've checked it worked by git-cloning a fresh version of master, and it all works.
I've added you in in the readme, thanks for the contribution :)

**Comment by veselignome** [comment]
Thank you :+1: 

Actually, this is my first filing an issue and contribution :)
And it feels great xD

Getting involved in open source... finally :)
