### ISSUE TITLE
The only language selection available is German

### ISSUE THREAD

**Issue by cindyccook** [antoinejaussoin/retro-board#131]
The only language selection available is German

**Comment by antoinejaussoin** [comment]
I'm not sure what you mean:

Can you please elaborate? What browser are you using?

<img width="141" alt="Retrospected_-_A_fun_way_to_retrospect" src="https://user-images.githubusercontent.com/110254/86969194-50d1b600-c165-11ea-8b8c-03b3428d8eb8.png">

**Comment by cindyccook** [comment]
The same one that I have always used, Chrome. Here is a screenshot:
[cid:image002.png@01D65540.74D78E80]

Kind regards,
Cindy Cook CSM, SA, LSSGB, MBA
Agile Project Manager, Business Applications
19001 Crescent Springs Dr | Kingwood, TX 77339
OFFICE: 281-312-7647 CELL: 281-623-9928
[cid:image001.png@01D65540.5924CC20]<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.insperity.com%2F%3FelqTrackId%3D981051bce0544cd9837956368e3ef088%26elqTrack%3Dtrue&data=02%7C01%7CJordan.Long%40insperity.com%7Cd83cfc4f9ca74043ff0808d697e39240%7C895d9ea7ce114131829f33f878d784b2%7C0%7C0%7C636863401018373472&sdata=1leN00vLJzLhG3vDoTv%2BKu6vFHZH63YIhCaE5LqQ9f4%3D&reserved=0>

**Comment by cindyccook** [comment]
![Retrospected Issue](https://user-images.githubusercontent.com/53021423/86970036-57940500-c134-11ea-983c-209437242853.PNG)

**Comment by antoinejaussoin** [comment]
Are you using retrospected.com, or are you deploying on your own machine?
If you are using retrospected.com, can I have the URL?

**Comment by cindyccook** [comment]
https://www.retrospected.com/game/wohz7_hoR

**Comment by cindyccook** [comment]
I have not changed anything on Chrome. I just clicked the flag and it let me change to English. So Strange. Sorry for bothering you.

Kind regards,
Cindy Cook CSM, SA, LSSGB, MBA
Agile Project Manager, Business Applications
19001 Crescent Springs Dr | Kingwood, TX 77339
OFFICE: 281-312-7647 CELL: 281-623-9928
[cid:image001.png@01D65549.3A981FB0]<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.insperity.com%2F%3FelqTrackId%3D981051bce0544cd9837956368e3ef088%26elqTrack%3Dtrue&data=02%7C01%7CJordan.Long%40insperity.com%7Cd83cfc4f9ca74043ff0808d697e39240%7C895d9ea7ce114131829f33f878d784b2%7C0%7C0%7C636863401018373472&sdata=1leN00vLJzLhG3vDoTv%2BKu6vFHZH63YIhCaE5LqQ9f4%3D&reserved=0>

**Comment by cindyccook** [comment]
Now it let me change the language by clicking the flag. Sorry for bothering you.

**Comment by antoinejaussoin** [comment]
@cindyccook no worries, glad it's working :)
