### ISSUE TITLE
Feature: Would be nice to have voted Issues ordered automatically

### ISSUE THREAD

**Issue by 42robotsCS** [antoinejaussoin/retro-board#138]
It would be a nice feature to have a template option to have issues/cards automatically ordered by the number of votes (most voted on top).

**Comment by antoinejaussoin** [comment]
I would think that's what the "Summary mode" is for. Also, if we do that, cards will move all the time as people are voting, even if you are in the middle of editing one or voting for one, so I don't think I'm going to implement that, sorry!
