### ISSUE TITLE
Feature: Allow to remove Vote (change mind)

### ISSUE THREAD

**Issue by Xyaren** [antoinejaussoin/retro-board#149]
Title basically tells it all.
I would like a Feature that allows to revoke a vote and spend it on the same ticket again or a different ticket.

**Comment by Doogiemuc** [comment]
+1   defeneitely needed feature

**Comment by vadamovsky** [comment]
When will this feature be implemented? We are eagerly waiting for it.

**Comment by antoinejaussoin** [comment]
I'll get working on it soon. Stay tuned.

**Comment by antoinejaussoin** [comment]
#457
