### ISSUE TITLE
Firefox Specific Bug: (hidden for now)

### ISSUE THREAD

**Issue by courtney-thwaites** [antoinejaussoin/retro-board#154]
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/67245901/96203111-8a645980-0fbd-11eb-921a-33ac96acbde4.png)

As a user I can view the cards in the summary, but I am unable to view the text on the board so I cannot view what I am voting on. This issue does not appear to affect Chrome as I was able to change browsers and continue participating in the retro.

**Comment by antoinejaussoin** [comment]
Thanks so much for reporting this, it is indeed a very serious bug, making the whole app unusable on Firefox.
I've just made a fix, and I will push it to prod in about 30 minutes.

Thanks again!
