### ISSUE TITLE
Docker image doesn't work

### ISSUE THREAD

**Issue by mamumumam** [antoinejaussoin/retro-board#158]
I tried out the docker image as described in the manual, but the server doesn`t work.
The frontend does show up but I can`t start any retro. pressing login leads to a anonymous login after entering a user name nothing happens when pressing the button.
any hints what could be wrong?

**Comment by antoinejaussoin** [comment]
Can you post some logs perhaps? do `docker logs <yourcontainerid>`

**Comment by mamumumam** [comment]
To be honest, I totally forgot this issue meanwhile. Shame on me!

I could manage to make it work, but not 100% sure how I could manage to do. 
As far as I can remember I did remove several images and containers as well as the unused  volumes. I think removing the volumes was the clue at the end. 

I guess there were parallel postgres containers/images which created a side effect on this one. 
Sorry for the missing feedback on the "solution" and any inconvenience caused by this.
