### ISSUE TITLE
Feature: Use the board Title as the page meta-title

### ISSUE THREAD

**Issue by sam-pires** [antoinejaussoin/retro-board#167]
Hello, 

First I'd like to thank you for this tool! It's great!!!

Here is a feature suggestion. Nothing critical but maybe you or someone might be interested too and we could discuss it.

**Context and Problem:**
- We create boards every 2 weeks for our retro. And we use the week in the board title to be able to find them easily in the dashboard or to quickly check we are on the right one when opening a board.
<img width="1132" alt="Capture d’écran 2020-11-10 à 12 27 53" src="https://user-images.githubusercontent.com/25405887/98668696-8aebd800-2350-11eb-8fb8-7100ab00a7a9.png">

- Though, I usually go to the board by typing directly "retrospected" in my browser, the problem is I see a list of retrospected link, but nothing allows me to know which board is for which week, see:
<img width="973" alt="Capture d’écran 2020-11-10 à 12 19 08" src="https://user-images.githubusercontent.com/25405887/98668708-8e7f5f00-2350-11eb-81f0-7d1f8a37e330.png">

**I wish I could quickly identify in the boards' titles or URL which week the boards are about**

**Suggestion**
- Update the meta-title of a board using the board title
I realized I was doing the same when going to a Google Sheet of Gdoc file, I type "Sheet" in the browser and I can identify the files because the title is displayed in the meta-title.
So I thought that could be great to have that in Retrospected.

<img width="918" alt="Capture d’écran 2020-11-10 à 12 28 58" src="https://user-images.githubusercontent.com/25405887/98668720-9212e600-2350-11eb-8b99-faf6eafcf30c.png">

Let me know what you think!

Cheers

**Comment by antoinejaussoin** [comment]
This is an excellent idea! And it shouldn't be too difficult to implement. Will try to get that in soon.

Thanks!

**Comment by sam-pires** [comment]
Awesome!
Thank you!

**Comment by antoinejaussoin** [comment]
@sam-pires all done (https://github.com/antoinejaussoin/retro-board/pull/168), but it will only ship with the v4, some time in December. Stay tuned!
