### ISSUE TITLE
Feature: filter

### ISSUE THREAD

**Issue by ayxos** [antoinejaussoin/retro-board#171]
It would be great if the app allows you to filter by author, We do retros with 20 people and finding your own tickets it is sometimes a tedious task

**Comment by antoinejaussoin** [comment]
Great idea! I could indeed add a search functionality that would work on the content and the author. 

Will think about how to do that and try to get that in for v4.

**Comment by ayxos** [comment]
Great! thanks :)

Also, it would be great if we can either change the front page, either show just a proper login page, so users will see the login directly and not as popup.

P.S great job, we use it very often

**Comment by antoinejaussoin** [comment]
The front page is kinda important actually for marketing purpose (it's a landing page really, that Google can parse), but I could make the login button more prominent.
What is the actual problem of having it the way it is currently? (I'm genuinely interested in knowing the actual reason so I can improve it!)

**Comment by ayxos** [comment]
I totally understand the marketing purpose, but on our daily basis, it is a extra step that we are kinda force to do.
Instead I would suggest a clean login page with a banner at the bottom or a "powered by ...: bottom line, that would do the effect and would be less invasive. Also keep in mind that the other members might not be developers, so they won't be interested on the product either way

(again, not my project and I do understand the idea of promoting it)
