### ISSUE TITLE
Voting on groups (or show running total of votes on tickets within the group)

### ISSUE THREAD

**Issue by jghaanstra** [antoinejaussoin/retro-board#183]
It would be nice if users could vote on a group (or show running total of votes on tickets within the group). This would allow for easier priorization.

**Comment by antoinejaussoin** [comment]
This already exists on the Summary Tab:

<img width="530" alt="Screenshot 2020-12-05 at 20 59 43" src="https://user-images.githubusercontent.com/110254/101265255-d53c5b00-373c-11eb-8698-759dac6e4db1.png">
