### ISSUE TITLE
Idea: Allow addition of actions to the retro

### ISSUE THREAD

**Issue by dc99dc99** [antoinejaussoin/retro-board#21]
As a team we discuss all the retro items and create actions off them on the board. Since the board is persistent , it would be great to be able to add the actions we decided directly to the board somewhere as a record of what we're going to do off the back of those retro items.

**Comment by antoinejaussoin** [comment]
Good idea! Will try to come up with a UX that makes sense for that and implement for the next release

**Comment by lukewrites** [comment]
Hi, Antoine, thanks for the wonderful tool! Any progress on this feature request? If you have a branch, I'd be happy to take a look at it.

**Comment by antoinejaussoin** [comment]
Hi Luke, not yet, but it should be an easy one to do (it would only have taken me 3 years!), will plan this for the next version. I know I said that in 2016 already, but I mean it this time ;)

**Comment by antoinejaussoin** [comment]
@lukewrites : I created a PR about this, let me know what you think, and if that was what you had in mind.

**Comment by antoinejaussoin** [comment]
Released on v2.0.2 and live on retrospected.com as of about 5 minutes ago
