### ISSUE TITLE
Feature request: re-ordering of ideas/issues

### ISSUE THREAD

**Issue by jfritz** [antoinejaussoin/retro-board#22]
As a retrospective facilitator, I want to be able to re-order the items on the board and have team members see the ordering change, so that my team can have a better visual indicator of similar issues.

**Comment by MattVane** [comment]
+1 
We usually group tickets by an emerging "theme" once they are all collected, which means similar concerns can be counted in aggregate. Reordering would be a decent stab at this, but grouping would be really good.

**Comment by antoinejaussoin** [comment]
Duplicate of https://github.com/antoinejaussoin/retro-board/issues/75, I haven't decided yet if I'm going to persist ordering or just create groups (without a specific order within them)
