### ISSUE TITLE
Delete board as anonymous user

### ISSUE THREAD

**Issue by dwettstein** [antoinejaussoin/retro-board#229]
As an anonymous user, I cannot delete my own board.

![image](https://user-images.githubusercontent.com/412133/111594442-5ccd4780-87cb-11eb-8db9-f9f94b6ffe1f.png)

**Comment by antoinejaussoin** [comment]
Hi!

So it's not possible at the moment, because anonymous account can be easily impersonated by anyone else.
I need to find a way to make them a bit more secure, to ensure that a random person cannot delete anyone else's boards.

**Comment by antoinejaussoin** [comment]
I suggest using a "real" account if you want more control over your data
