### ISSUE TITLE
Last item entered does not save. When I access the link, it is gone.

### ISSUE THREAD

**Issue by cindyccook** [antoinejaussoin/retro-board#232]
Last item entered does not save. When I access the link, it is gone.

**Comment by antoinejaussoin** [comment]
Can you please be more specific? And make sure you can reproduce this bug?

**Comment by cindyccook** [comment]
I ignored it the first time it happened, but then it happened again, so I did reproduce it. Can I do it reliably? The last item that I added was there when I returned. The only thing that I can think is if I edit an item and the app times out on me and disconnects me, maybe it would not save it. 

BTW, the app randomly disconnects all the time on some sessions. And no, I don't know how to reliably make it do that. I just observe it in our team that people complain, and it has happened to me on some sessions.

**Comment by antoinejaussoin** [comment]
Hi Cindy,

Thanks for your feedback. I overhauled a lot of the logic for the upcoming 4.2.0 release which will add safety measures to ensure that an item is not dropped or not persisted.
As for the regular disconnections, it's a bit concerning indeed: your browser will actually (on purpose) actively disconnect the websocket connection if you change tab or minimise your browser for more than a few seconds, so could it be that?
Or is it disconnecting in the middle of a session, when you have your browser in the forefront?
I'm going to add some logging to get a better sense of how often that happens.

Again, thanks for the feedback!

**Comment by cindyccook** [comment]
It is disconnecting in the middle of a session, when you have your browser in the forefront.

**Comment by antoinejaussoin** [comment]
I've deployed release 4.2.0 which should address (or at the very least record) these kind of issues
