### ISSUE TITLE
Some users can't post messages

### ISSUE THREAD

**Issue by do606** [antoinejaussoin/retro-board#246]
Multiple users logged anonymously, some of them can't post messages in various sessions in a row.

**Comment by antoinejaussoin** [comment]
Do you have any error message coming up by any chance?

**Comment by do606** [comment]
Unfortunately no, but this problem is lasting for more than a month already. After the input is provided, enter doesn't fire any action (or error). The message stays in input. It occurs in Chrome, Edge and Firefox. Clearing cookies didn't help nor anonymous login on different machine.

**Comment by antoinejaussoin** [comment]
Do you know how to open the Developer Tools in Chrome? I would be curious to see if there is any error on the console?

**Comment by antoinejaussoin** [comment]
Also, when you come back to the home page, do you have a "free allowance reached" message like so?

<img width="698" alt="My_Retrospective_-_Retrospected" src="https://user-images.githubusercontent.com/110254/113691078-fcdc0980-96c3-11eb-95e9-a95c28e88073.png">

**Comment by do606** [comment]
there is no error and on homepage I have only Welcome,... and previous Retrospectives. It's the same for 'older' user as for new one

**Comment by antoinejaussoin** [comment]
This is going to be difficult to debug unless I can see the issue with my own eyes. Would you be happy to spend 15 minutes sharing your screen in the following days?
I will be very happy to offer you a lifetime Retrospected Pro subscription for free, for the help provided.

**Comment by do606** [comment]
Yes I can share my screen, I know it's hard to identify issue when there's nothing I can give you apart of the fact that something appears to not work as intended.

**Comment by antoinejaussoin** [comment]
Which time-zone are you in? I'm in London

**Comment by do606** [comment]
CET, what is your preferred way of communication?

**Comment by antoinejaussoin** [comment]
Google Meet? You can reach me at "antoine at jaussoin dot com" by email so we can schedule this :) thanks a lot for the help

**Comment by antoinejaussoin** [comment]
Thanks again @do606 for the time spent on the call, this was extremely helpful.
I've added support for Numeric Enter, and will release that this weekend (I usually don't release mid-week to prevent unnecessary downtime).
