### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by maxwellb** [antoinejaussoin/retro-board#26]
Provide support for (and on retrospected.com provide one) a Privacy Policy, and perhaps also Terms of Use, to be authored, linked.

**Comment by mventuri** [comment]
Hi @maxwellb , I found this freemium service for privacy policy:
https://www.iubenda.com/en/
Maybe it can help.
Thanks,
Marco

**Comment by antoinejaussoin** [comment]
@maxwellb I've finally added the policies to retrospected.
I didn't use iubenda at the end (it's horrendously expensive, like 450 USD per year for a personal account with GDPR support!), but went for the totally free (for non commercial website) websitepolicies.com.
