### ISSUE TITLE
Floating button is hidden in Summary page

### ISSUE THREAD

**Issue by hieuwu** [antoinejaussoin/retro-board#262]
As this screen shot, in the Summary page, the floating button is hidden by a white space at the bottom
![floating-button-is-hidden-by-white-space](https://user-images.githubusercontent.com/43868345/117284154-bd563800-ae90-11eb-9d55-0161bfbb4f81.png)

**Comment by antoinejaussoin** [comment]
Well spotted, thanks! Will fix in the next version
