### ISSUE TITLE
Feature request: Reverse order of posts

### ISSUE THREAD

**Issue by konrad44** [antoinejaussoin/retro-board#272]
When users write their posts on boards they appear at the bottom of the stack. Quickly they vanish from view and require scrolling to reach. It limits board potential to support brainstorming-like sessions as users don't see each others newest posts.
A solution to this would be an option in board settings that allows for reversing default order of posts so that newest posts would appear on top rather than at the bottom of the stack.

**Comment by antoinejaussoin** [comment]
This is an excellent idea. Could even be the default actually. Will look into it. Thanks!

**Comment by antoinejaussoin** [comment]
This should be in prod now! Thanks again for the idea.
