### ISSUE TITLE
Clarify licensing for self-hosted deployments

### ISSUE THREAD

**Issue by csomh** [antoinejaussoin/retro-board#295]
Hey :wave: 

We are using retrospected in my team to do our sprint retros, but soon we are going to reach the end of our free tier of the service.

I thought to build and deploy retro-board for our own use, on our own infra. Given the license is GPL-3.0, this should be possible, but then I found "You must obtain a self-hosting licence." as a [pre-requisite for self-hosting](https://github.com/antoinejaussoin/retro-board/blob/1b61b48f69d857ed58e8939c0fdb8cd3976465d5/README.md#prerequisites--1) in README.md. To me this seems to go against GPL-3.0, [which says](https://github.com/antoinejaussoin/retro-board/blob/1b61b48f69d857ed58e8939c0fdb8cd3976465d5/licence#L158) (among other things), that "This License explicitly affirms your unlimited permission to run the unmodified Program."

Can you please clarify what the licencing terms for a self-hosted deployment are?

Thank you a lot, and huge kudos for making retrospected available to all of us! :unicorn: :rocket:

**Comment by antoinejaussoin** [comment]
Hi Hunor,

Thanks for this very good question!
So, GPL doesn't forbid selling software:
"Yes, the GPL license allows users to sell the original as well as the modified software. It may be confusing, but free software is referred to as free in terms of freedom and not in terms of price. As Richard Stallman explains it, free software means free as in “free speech,” not free as in “free beer.”

Basically, individual or companies can either:
- Fork this repo, modify it (and remove the licence warnings etc.) and deploy as they see fit
- Use www.retrospected.com for a fee (a subscription), if they don't want the hassle of having to deploy themselves
- Or use the turn-key Docker images that I provide for a one-off fee. 

Charging (usually corporations) helps keep this software alive, and free for people like yourself.

Hope that helps,

Antoine

**Comment by csomh** [comment]
Thank you for the explanation, Antoine!
