### ISSUE TITLE
Help with install...

### ISSUE THREAD

**Issue by jonljh** [antoinejaussoin/retro-board#34]
I followed your instructions to install, but when I run npm run build I see the following error.  Any thoughts?

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! retro-board@1.0.1 lint: `eslint --ext .js --ext .jsx .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the retro-board@1.0.1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-12T17_51_01_714Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! retro-board@1.0.1 build: `cross-env npm run lint && cross-env npm run build-server && cross-env NODE_ENV=production webpack --config webpack.prod.config.js --progress --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the retro-board@1.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-12T17_51_01_748Z-debug.log`

**Comment by antoinejaussoin** [comment]
Hi ! I've tried to reproduce, but everything is working fine both on the develop branch and the master one.
One thing to keep in mind is the develop branch needs Node to be on version 10 or higher, while the master branch needs 9 max (and not higher). I will fix that.

In the meantime, if you still have problems, could you please send me your debug log file?  The error seems to be related to linting, but it's difficult to know what's going wrong without seeing the log.

THanks!

**Comment by jonljh** [comment]
Thanks for the quick response!  So I started all over and the install seemed to complete successfully with no issues.  When I run **npm run start-server** everything appears to run fine:

> npm run start-server
> 
> > retro-board@1.0.1 start-server /lab/retro-board
> > nodemon ./server/server-dev.js
> 
> [nodemon] 1.18.4
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching: *.*
> [nodemon] starting `node ./server/server-dev.js`
> 💻   Using NeDB database
> Server started on port 8081, environement: dev
> 

but when I go to the website I just saw a purple page with a pulsing icon:
![image](https://user-images.githubusercontent.com/23063271/45687778-98fd8f80-bb1d-11e8-8623-8ba0c5fa3256.png)

**Comment by jonljh** [comment]
I started over and everything looks good.  I didn't realize I was running it in development mode also.  Everything seems to be working great.  Thanks for this great product!
