### ISSUE TITLE
Lost previously entered retrospectives

### ISSUE THREAD

**Issue by Paultify** [antoinejaussoin/retro-board#35]
Hi there,

My colleague Kevin recently logged into his retrospected.com and observed his previous retrospective details her recorded (three in total) disappeared.

Is there any possible way of retrieving them? 

Thanks

**Comment by Ryudo302** [comment]
Same here, but I noticed this error in the browser console log when I try to access any retrospective:

`WebSocket connection to 'ws://retrospected.com/socket.io/?EIO=3&transport=websocket&sid={ID}' failed: Error during WebSocket handshake: Unexpected response code: 403`

**OBS.:** `{ID}` is the ID of the retrospective session.

Tested in Chrome and Firefox.

**Comment by antoinejaussoin** [comment]
Hi guys, I indeed had a serious issue with my server, and I'm working to restore the database right now. It should merge the sessions created from yesterday and today as well, minimizing the loss of data. 

Sorry for that!!

**Comment by antoinejaussoin** [comment]
DB Restore is now complete, you should be able to view your old sessions again.

Sorry again!
