### ISSUE TITLE
Security: Upgrade JQuery >= 3.5.0

### ISSUE THREAD

**Issue by jdsatava127** [antoinejaussoin/retro-board#350]
Our Tenable security scanner is flagging Retroboard for utilizing JQuery 3.4.1. There are known XSS vulnerabilities in this version as described in https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/. Please upgrade to JQuery 3.5.0 or newer.

We are running version 3.10.0 in a self-hosted environment with docker containers.

**Comment by antoinejaussoin** [comment]
Hi @jdsatava127,

Thanks a lot for your report. I have upgraded jQuery to the latest version, and merged to dev.
I'm planning to release a new version to master (and to Docker) sometimes over the weekend, with the fix.
