### ISSUE TITLE
Allow sending mails through custom mailserver

### ISSUE THREAD

**Issue by dayByte** [antoinejaussoin/retro-board#365]
like the option to use sendgrid there should be an option to define a own mailserver

**Comment by antoinejaussoin** [comment]
Sendgrid and a custom mail server are two (very) different ways of sending emails, so we won't be adding this feature for the foreseeable future. I would recommend subscribing to SendGrid (it's free, and easy to do, if you follow the documentation here: https://docs.retrospected.com/docs/self-hosting/sendgrid).

**Comment by antoinejaussoin** [comment]
I have changed my mind, I'm implementing it :) @dayByte
