### ISSUE TITLE
Running in Docker Container

### ISSUE THREAD

**Issue by ultimatemanu** [antoinejaussoin/retro-board#39]
Bonjour,

Just a question regarding running your great retro-board project in a Docker container.
I have allowed me to make a fork of your project and have put a Dockerfile for building a docker image and running it.
https://github.com/ultimatemanu/retro-board

If you are interested you can of course pick-up the `Dockerfile` and `dockerignore` files and copy them to your master. You will find a small doc in the readme file of the fork.

Thanks again and cheers

Emmanuel Comba

**Comment by antoinejaussoin** [comment]
Bonjour!

Thanks for your message :) Funnily enough, I've been thinking exactly the same, and, while re-writing retro-board (v2), I added Docker files and docker-compose:

https://github.com/antoinejaussoin/retro-board/tree/v2

The v2 can be completely instantiated with production settings, postgres as a database, and even a postgres web admin (pgAdmin) from a single docker-compose file.

If you have more familiarity with Docker, please don't hesitate to have a look at my various docker files to see if there isn't something to improve! I'm quite new to it.

Merci !

Antoine

**Comment by ultimatemanu** [comment]
Excellent, merci beaucoup Antoine :)

I will get a look at your branch. I let you know.

Bonne soirée!

Emmanuel

**Comment by antoinejaussoin** [comment]
v2 has been released, all "dockerised" now :)

**Comment by ultimatemanu** [comment]
Thanks a lot I will test this tomorrow !
