### ISSUE TITLE
Session title

### ISSUE THREAD

**Issue by Sonaryr** [antoinejaussoin/retro-board#4]
I love the idea about this project and would love to introduce it in our team(s), but I sometimes work on different teams and therefor I need to do more than 1 retro.
Being able to differentiate them would become easier if the sessions are titled.

**Comment by antoinejaussoin** [comment]
There’s actually a “hack”: you can put whatever you want in the URL after /session/

For example:
http://www.retrospected.com/session/hello_maarten

That means you can effectively name your session, but be careful to take a name that’s not likely to be found by someone else :)

-- 
Antoine Jaussoin
Sent with Airmail

On 4 April 2016 at 08:20:01, Maarten Schroeven (notifications@github.com) wrote:

I love the idea about this project and would love to introduce it in our team(s), but I sometimes work on different teams and therefor I need to do more than 1 retro.
Being able to differentiate them would become easier if the sessions are titled.

**Comment by antoinejaussoin** [comment]
I'll probably revisit the "create a new session" page at some point to make this hack a little less hacky, and allow users to choose their session name from the page itself

**Comment by antoinejaussoin** [comment]
I've improved the "create session" page (on the develop branch), so you can now create a custom session with the name you want. I'm waiting a few days for some translations to be done but will expect to release that on retrospected.com by the weekend.

**Comment by Sonaryr** [comment]
I've seen the changes, but I predict alot of conflicts with just setting the title as the session...
Say that I for example want a retro for sprint 1 and call my session "Retro Sprint 1", and now you come along and wants the same. You will just enter my retro and won't be able to create your own.

What I was thinking about was really keeping the uuid as session identifier, but just be able to add a title to it (and persist it to the DB). That way multiple users can name their sessions the same and still have unique retro's

**Comment by antoinejaussoin** [comment]
I see what you mean, and I'm still debating the issue between me, myself and I.

Basically, I want to keep the website as simple as possible, and having a URL you can remember and share verbally (i.e. without the whole made-up ID) was part of that goal.
That being said, you are entirely right that we'll have conflicts, and users will need to create pseudo-unique names.

Another way would be to let the user enter any name, ask the server if it does exist, and then return it with a suffix if it does (i.e. let say the user enters "retro", but "retro" and "retro1" already exists, so the server would return something like "retro2"). 

Other option would be that when you enter the name, the server is asked if it does exist, and displays a warning (and disable the create session button) until the user comes up with a new name.

What do you think?

**Comment by Sonaryr** [comment]
Ok, but now think of me as a malicious person.
I find out this mechanism and find a name that is in use. Now I can access that retro and start messing with it.

Just thinking about possible things that could go wrong.

**Comment by antoinejaussoin** [comment]
Indeed, but if I really wanted to be secure, I would create logins and registration, and SSL, which is not what I want: I want to leave it as open as possible, so users can create new sessions in seconds, not minutes.

This indeed leave the possibility of a hack. Without registration and proper security, anyone can indeed access anyone else's session, which, considering the goal of this system, is a fair trade-of.

If a user wanted to have a "secure" session, then they'd have to either come up with a complicated and un-guessable name, or keep using the generated uuid (security by obfuscation). 

Let see the problem in a different way: yourself, as a potential user, would you NOT use this system because having no registration leaves your session to be accessible by anyone?
Would choosing a session name such as '<your company>-<your team>-<date>' be enough? (for example "microsoft-windows-team-retro-2016-04-07") ?

**Comment by Sonaryr** [comment]
I'm not saying it should be super secure with login etc.
But I just like the idea that is in place with UUID I don't think anyone will type in the url so in my eyes the url can be like it was in the beginning, but just that on the page the title is there.

**Comment by antoinejaussoin** [comment]
I tried both (on two different branches), and indeed I think I like your approach more.
In any case, if a user wants to "hack" the URL and add a custom session, he can do it anyway.
But indeed, for regular users, having a made-up ID is better. I just took a different ID generator to have a shorter one, so it looks better (see my latest branch)

**Comment by antoinejaussoin** [comment]
Version 0.4.1 is out, which basically does what you suggested :) It's indeed better this way. I'll close this issue!
