### ISSUE TITLE
Add multiple actions

### ISSUE THREAD

**Issue by andyk314** [antoinejaussoin/retro-board#43]
Is there a way to have multiple actions/comments?

**Comment by antoinejaussoin** [comment]
mmh there might be a bug that prevents creating a new line. I need to allow a user to enter multiple lines so you can create a list of actions. Will have a look shortly!

**Comment by antoinejaussoin** [comment]
Hi @andyk314 , thanks for your patience, I (finally) fixed the issue by allowing multi-line actions (and posts!) by using the "shift" key. That way you can now create a list of actions:

![image](https://user-images.githubusercontent.com/110254/66274963-f5903180-e87b-11e9-8a6e-c643e9306887.png)

Hope that helps!
