### ISSUE TITLE
doesn't work on windows/mac

### ISSUE THREAD

**Issue by srraf** [antoinejaussoin/retro-board#44]
trying to get  a working example running but having different errors on windows and linux. 

i tried cloning and then running `yarn` followed by `yarn start`

results on mac/windows: 

```
$ yarn start
yarn run v1.17.3
$ yarn build-common && yarn start-server & yarn start-ui
$ cd retro-board-common && yarn build && cd ..
$ rm -rf dist && ../node_modules/typescript/bin/tsc --build
'..\node_modules\typescript\bin\tsc' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ yarn build-common && cd retro-board-app && yarn start
$ cd retro-board-common && yarn build && cd ..
$ rm -rf dist && ../node_modules/typescript/bin/tsc --build
'..\node_modules\typescript\bin\tsc' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

it does work on Linux!

**Comment by antoinejaussoin** [comment]
Can you confirm:
- That you switched to the master branch (`git checkout master`)
- Your Node version (mine is 12.9.1)

I've tried checking out master and `yarn` followed by `yarn start` and it works for me (on a Mac).
Haven't tried with a PC though!

**Comment by antoinejaussoin** [comment]
@srraf ?

**Comment by antoinejaussoin** [comment]
Can you tell me your node version by running `node -v`? I wonder if it has something to do with that!

**Comment by srraf** [comment]
certainly 

`v12.9.1`

**Comment by jesusabp** [comment]
It works for me on Mac (master and develop).

I found the same issue as @srraf on Windows; I did the changes in the image **...\retro-board-common\package-json** (I suppose **tsc** command's folder is included in the Windows Path) and it is fixed: 

![image](https://user-images.githubusercontent.com/49287354/68212792-076b0e80-ffb9-11e9-85c8-30e6a86afc58.png)

**Comment by antoinejaussoin** [comment]
It should be all fixed now, I've tested on my windows box and it seems to work. Fix is only on develop for now, will merge to master on the next release.
