### ISSUE TITLE
No longer saving entries, including title

### ISSUE THREAD

**Issue by cindyccook** [antoinejaussoin/retro-board#45]
No longer saving entries, including title. See screenshots. ![Capture Retrospected](https://user-images.githubusercontent.com/53021423/65443395-9c43ef00-ddf3-11e9-96ed-676623dc5775.PNG) Entries are made. Open a new tab and enter the same URL: https://retrospected.com/game/1YmCr7zx4 It is blank now.

**Comment by antoinejaussoin** [comment]
That was pretty bad... thanks so much for letting me know. Basically the server had run out of space (it's a pretty small machine!). I've cleared some, and will make sure it doesn't happen again.

Thanks again!!!

😓

**Comment by antoinejaussoin** [comment]
Looks like from the database that it didn't work for the last 48 hours (good thing it was during a weekend...)

Should be all good now, will investigate why something seems to be eating a lot of space in one of my docker container.

**Comment by antoinejaussoin** [comment]
@cindyccook : Fixed it now for good, limiting the log size directly from docker-compose. Thanks again for your feedback, very much appreciated.

**Comment by cindyccook** [comment]
Thank you so much for the rapid response!

Kind regards,
Cindy Cook CSM, SA, LSSGB, MBA
Agile Project Manager, Business Applications
19001 Crescent Springs Dr | Kingwood, TX 77339
OFFICE: 281-312-7647 CELL: 281-623-9928
[http://img.en25.com/EloquaImages/clients/Insperity/%7b84cfad67-a241-4a5f-8e9f-499deeedd911%7d_insperity-logo-for-email-signatures.jpg]<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.insperity.com%2F%3FelqTrackId%3D981051bce0544cd9837956368e3ef088%26elqTrack%3Dtrue&data=02%7C01%7CJordan.Long%40insperity.com%7Cd83cfc4f9ca74043ff0808d697e39240%7C895d9ea7ce114131829f33f878d784b2%7C0%7C0%7C636863401018373472&sdata=1leN00vLJzLhG3vDoTv%2BKu6vFHZH63YIhCaE5LqQ9f4%3D&reserved=0>
