### ISSUE TITLE
Feature request: Customized Number of Columns

### ISSUE THREAD

**Issue by jesusabp** [antoinejaussoin/retro-board#46]
As a retrospective facilitator, I want to define the number of columns shown in my board in order to be able to play different kinds of Restrospective's formats.
E.g.:
"went-well, Didn't-Go-Well"                      (2 columns ),
"Start, Stop, Continue"                             ( 3 columns ),
"Liked, Learned, Lacked, & Longed For" ( 4 columns ),
Sailboat: "anchor, cargo, islands, winds, rocks" ( 5 columns ).

(Maybe the number of cols could be changed for the same Retro session showing/hiding the selected columns) 
![image](https://user-images.githubusercontent.com/49287354/68064165-d9ef3e00-fcf6-11e9-94d3-0a3c02cb4701.png)

**Comment by antoinejaussoin** [comment]
Getting there!

<img width="310" alt="Retrospected_-_A_fun_way_to_retrospect" src="https://user-images.githubusercontent.com/110254/68085541-e16b3000-fe39-11e9-9adc-6fb4b6e8b606.png">

**Comment by antoinejaussoin** [comment]
Now in the develop branch. Launching to retrospected very soon.
