### ISSUE TITLE
Show user name of creator on the card

### ISSUE THREAD

**Issue by zalexki** [antoinejaussoin/retro-board#47]
Hey, nice job ! 

What do you think about adding the name of the card creator on it ?
I would see it in the bottom right of the card for normal view and at the beginning of the line for summary.
This also can be an option on the side perhaps ?

**Comment by antoinejaussoin** [comment]
Thanks :) That's actually a good idea, I'll add it as an option (I'm introducing customisation in the next release, most of it is already on the develop branch).

Thanks!

**Comment by jesusabp** [comment]
Yeap, having it as an **option** sounds good because sometimes collecting the feedback in anonymous manner is easier.

**Comment by antoinejaussoin** [comment]
@zalexki , @jesusabp : now available at https://beta.retrospected.com/, soon on the main website

**Comment by jesusabp** [comment]
@antoinejaussoin thats Great!

I was playing a little and it seems that persistence for likes / dislikes is not working after logout.
- I have spend the likes/dislikes
- I logged out
- I login again and my likes/dislikes are reseted (disapeared from post)

**Comment by zalexki** [comment]
i experienced one desync on one like no logging in/out. can't reproduce tho.

**Comment by antoinejaussoin** [comment]
I think I fixed the issues with voting, let me know if it happens again! It's all in production now, so hopefully it was a glitch... I'l test more over the weekend. Thanks guys! (I mentioned you in the readme btw).
