### ISSUE TITLE
Votes are not stored

### ISSUE THREAD

**Issue by dkistner** [antoinejaussoin/retro-board#56]
First of all thanks for sharing this project. Pretty awesome and helpful.

I have found an issue, where it seems that the up and down votes of people which don't add an item to the board are not stored.

#### Steps to reproduce
1. Add a new board and add a item to the board
2. Access as another user the board (e.g. via another browser)
3. Up or down vote the item
4. Refresh the page. The vote information seems to be gone

--- 
Btw: I found another thing, but I do not know if the behaviour is by intention or a bug. A user can't re-vote. That means a user is no able to remove it's own votes and distribute them once more.

**Comment by antoinejaussoin** [comment]
Hi @dkistner ,

First of all, many thanks for reporting this!
I've been trying to reproduce though, and I can't seem to: 
https://youtu.be/_RjO5c3s0zA

I'll try different scenarios, but can you double check if you can consistently reproduce that bug with the given scenario? Which browser are you using?
You can also try clearing your browser's cache, you might have an old version of the client?

Also - for the re-vote, you can't indeed (by default) vote again on the same post, but a user can (by default) vote on every other posts.
This setting can be changed if you create a custom session from the home page (allowing multiple votes on the same post, or restricting the user to only one vote overall, and everything in between).

**Comment by antoinejaussoin** [comment]
I've also purged the Cloudflare cache in case it helps making sure you get the newest client code

**Comment by dkistner** [comment]
Hi @antoinejaussoin, 

thanks for following up. I have tried it once more and still come to the conclusion.
I use version 2.1.3 of the retro-board and access it via Chrome 78 on osx.
Maybe it is related to my setup. I run the board and the Postgres on Kubernetes.

I will try to reproduce it locally and report feedback once more.

**Comment by antoinejaussoin** [comment]
Hi,

Can you try to repro on https://www.retrospected.com ? That should be version 2.1.4. If you can't repro there it means it could have been a bug on the previous version. And that could be related to a bug I fixed on that version (see changelog: "Bugfix: First post was sometimes not saved on regular sessions").

**Comment by antoinejaussoin** [comment]
So it seems you might be onto something, I had a retro on a self-hosted version of retro-board (also using K8s) and we experienced a loss of votes. I'll investigate further tonight, and issue a fix asap. That's pretty bad if that's the case!!

**Comment by antoinejaussoin** [comment]
Hi @dkistner,

I got to the bottom of this, and you were right, there was indeed a bug.
It should all be fixed now, please update your image to the latest (2.2.0) version.
Available on docker at antoinejaussoin/retro-board-frontend:2.2.0 and antoinejaussoin/retro-board-backend:2.2.0 (or use the latest tag).

Thanks again for reporting this!!

**Comment by antoinejaussoin** [comment]
actually I just realised I didn't mention you on the README, will make an update soon
