### ISSUE TITLE
Actions missing from export

### ISSUE THREAD

**Issue by MattVane** [antoinejaussoin/retro-board#70]
Actions (the most important part of the retro output!) are missing from the export features - both markdown and rich text...

**Comment by antoinejaussoin** [comment]
Not quite true! They are there, but are displayed with their respective posts, not as a separate block.

I must admit it's confusing that it's different from how I display them on the summary though, and I'm going to put them in a separate section as it is on the Summary.

<img width="609" alt="Retrospected_-_A_fun_way_to_retrospect" src="https://user-images.githubusercontent.com/110254/71249562-5d9bd300-2315-11ea-98bf-e5a129b5fbd1.png">


# Retrospected Session

## My Retrospective

### Session details:

**Date**: Friday, December 20th, 2019 at 10:42:14 AM GMT+00:00

**URL**: https://retrospected.com/game/gariybl8

**Participants**: Antoine

**Posts**: 3

**Votes**: 0

### Posts

  
#### What went well?



  
#### What could be improved?

- (+0/-0) A post
- (+0/-0) A post with an action
  - Action: Hello I'm an action
- (+0/-0) another post

  
#### A brilliant idea to share?
