### ISSUE TITLE
New Summary from top of page has carriage return after voting when copied

### ISSUE THREAD

**Issue by cindyccook** [antoinejaussoin/retro-board#71]
Could you remove the carriage return after the voting stats when summary is cut and pasted?

**Comment by antoinejaussoin** [comment]
Hi !

Can you let me know how you cut and paste?

I've added a functionality to generate a text version of the summary that goes directly into your clipboard, either in rich text (i.e. text with some formatting like bold), and Markdown:

<img width="638" alt="Retrospected_-_A_fun_way_to_retrospect_and_VENN_Sprint_Board_-_Agile_Board_-_Jira" src="https://user-images.githubusercontent.com/110254/71250570-e1ef5580-2317-11ea-8c72-5d0dfecca9f9.png">

I've checked the output of these 2 and I can't see any weird carriage return. Let me know if that solves your issue!

**Comment by cindyccook** [comment]
I have been control-c and control-v cutting and pasting the summary when you had to click the menu to get to the button to switch from normal to summary mode, pasting into OneNote, for years.  It looked like this: 
![image](https://user-images.githubusercontent.com/53021423/71272682-48c13e80-2319-11ea-9745-cf8610a3b42b.png)

Now that you put the control for summary mode on the page, when I use that, the same method generates the voting on a separate line from the content:
![image](https://user-images.githubusercontent.com/53021423/71274110-aa81a880-2319-11ea-886b-c533dbfb8db3.png)

**Comment by antoinejaussoin** [comment]
Cool, will see what I can do!
