### ISSUE TITLE
Ability to group items together into consolidated topics

### ISSUE THREAD

**Issue by evillgenius75** [antoinejaussoin/retro-board#75]
Many time in Retrospectives especially for large teams is to group common comments together into similar topic areas, then talking about the all up topic. It would be great to add an ability for whomever is running the retro able to create group topic cards and then drag and drop comments into group topic

**Comment by mschickensoup** [comment]
It's a great idea, I'd add that it's kind of annoying while during a session you can see that some of the cards relate to the same topic but you are not able to merge them. It would be amazing to add such ability.

**Comment by mgcode** [comment]
I did my first retro-board today, and for our team it was the only thing we were missing

**Comment by antoinejaussoin** [comment]
Looks like it's a popular idea, I'll try to get that in for the v3, will have a look at how I can achieve that.

Thanks for the feedback!
