### ISSUE TITLE
Disabling downvoting

### ISSUE THREAD

**Issue by imranismail** [antoinejaussoin/retro-board#77]
From the looks of it this isn't too hard to achieve considering maxDownvote is nullable. What do you think @antoinejaussoin ?

My organization needs this and I can contribute this feature.

**Comment by antoinejaussoin** [comment]
Actually I thought I did this already by limiting the number of down votes to 0 in the "Customise" panel, but it seems I put a minimum of 1 instead. It would indeed just be a matter of allowing 0 there I suppose! If you have some bandwith, I'm happy if you can make a PR (against develop), and I'll merge and deploy a new version.

**Comment by antoinejaussoin** [comment]
I implemented it as a quick fix and released a new version
