### ISSUE TITLE
Cancelling a like/dislike

### ISSUE THREAD

**Issue by imranismail** [antoinejaussoin/retro-board#82]
I'd like to contribute this feature. But before that, I'd like to brainstorm the UI and UX and perhaps gather some pointers on where I should look into in the codebase to implement this feature.

After reading a bit, am I right by thinking that here might be a good start for client-side changes:

https://github.com/antoinejaussoin/retro-board/blob/develop/retro-board-app/src/views/game/Post.tsx#L24-L25

Thanks again for spending your time on this @antoinejaussoin

**Comment by mschickensoup** [comment]
It would be great to have this feature! Thanks @antoinejaussoin for all your hard work. Much appreciated.
