### ISSUE TITLE
Being able to invite only the specific people to a session

### ISSUE THREAD

**Issue by mschickensoup** [antoinejaussoin/retro-board#93]
What I think is missing and would enhance security is that currently everyone with the link can join the session. I'd prefer to integrate this with Gmail e.g. and send invites to specific people only.

**Comment by antoinejaussoin** [comment]
And I completely agree. I'm working on the v3 at the moment, and added the ability to login using your social media account (currently supports Github, Google and Twitter, but might add some more).
That means I can now add this functionality pretty easily (it wasn't secure before with "anonymous" logins...)
