### ISSUE TITLE
Being able to use your own saved template that you can use for future sessions

### ISSUE THREAD

**Issue by mschickensoup** [antoinejaussoin/retro-board#94]
At the moment, there are four wonderful options to choose from the built-in templates:

1. Well / Not well
2. Start / Stop / Continue
3. Four LS
4. Sailboat (my fav <3 ) 

What if I would like to save the template I'm about to customize and use it for future sessions? I can't do that at the moment. What would be also great for future users is that they can also have a look at _other peoples templates_ available for either a) people from a certain domain (in a company) b) for public so I can see that this issue has a big potential when it comes to adding new features in regards to customization of a template or creating a one from scratch.

**Comment by antoinejaussoin** [comment]
That's a good idea as well, the first part is somewhat easy to implement, the second a bit harder and would probably come at a second stage. But they are both useful I think.

**Comment by antoinejaussoin** [comment]
Sort of done, the V3 will allow setting custom settings as "default", so when you create a session directly it uses these new defaults.

**Comment by mschickensoup** [comment]
Great! Thank you so much I'll be testing soon ;-)
