### ISSUE TITLE
Integration with giphy

### ISSUE THREAD

**Issue by mschickensoup** [antoinejaussoin/retro-board#95]
I think it would be much fun to integrate retro board with [Giphy](https://developers.giphy.com/), so that you can add something funny to the card you create. 

For sure, at the beginning, there should be a limited numbers of gifs you can add, so that there's not too much load or chaos.

Any thoughts? 👍

**Comment by mik-laj** [comment]
This may be a bit problematic because Giphy requires an API key, but yes. Let's do it. Gifs with cats are just as important as [photos with cats](https://github.com/antoinejaussoin/retro-board/issues/97). We could use https://sergiop.github.io/react-giphy-searchbox/

**Comment by mschickensoup** [comment]
Yeah, I wasn't sure about the API key when it comes to Giphy but the solution you suggested looks great and easy to implement.

**Comment by antoinejaussoin** [comment]
Excellent idea :) I love it. It should be easy enough that I can probably stick that in on the V3.
I'll try to make it work like Slack, where you can just type `/giphy` and have the search pop up.
