### ISSUE TITLE
Adding a picture to a customized column

### ISSUE THREAD

**Issue by mschickensoup** [antoinejaussoin/retro-board#96]
Sometimes as a facilitator, I'd love to customize a column to give a session a theme or better feel. Let's say a session is hard and I'd like to make people feel relaxed by showing them goofy stuff. The team I work with on a daily basis loves cats and I am not able to add any cats pics. It makes them super sad.

**Comment by mschickensoup** [comment]
Also, I think it would be better to do it from a view that doesn't exist yet ;-) I added the following [issue](https://github.com/antoinejaussoin/retro-board/issues/92) regarding customizing an already existing session. So let's say I am looking at a certain column at the moment and I'd like to put a png, jpg file under my question:

<img width="469" alt="Screenshot 2020-03-11 at 21 59 46" src="https://user-images.githubusercontent.com/50360982/76463602-f3f70680-63e3-11ea-9ae2-9ae4f056ac77.png">

It would be possible ofc when there's an editing option to the already existing session.

**Comment by nuclearpinguin** [comment]
Awesome idea!

**Comment by antoinejaussoin** [comment]
That's probably a bit trickier than the other suggestion, and might be a bit gadget at this stage! But will record it and decide later on if I implement that. Thanks!
