### ISSUE TITLE
Adding picture to a card

### ISSUE THREAD

**Issue by mschickensoup** [antoinejaussoin/retro-board#97]
I think it doesn't need a comment but what I mean by card is as follows: 

<img width="477" alt="Screenshot 2020-03-11 at 21 56 19" src="https://user-images.githubusercontent.com/50360982/76463138-323ff600-63e3-11ea-8abd-ce572099eaab.png">

**Comment by mik-laj** [comment]
Yes. I miss the option of adding photos of cats. This is a much awaited feature because cats are a serious matter.

**Comment by antoinejaussoin** [comment]
I'll do that as part of the Giphy one

**Comment by mschickensoup** [comment]
Great news! <3

**Comment by antoinejaussoin** [comment]
Duplicate of https://github.com/antoinejaussoin/retro-board/issues/95
