### ISSUE TITLE
Adding emoji next to textbox while customizing text field

### ISSUE THREAD

**Issue by mschickensoup** [antoinejaussoin/retro-board#98]
Right now there are many great icons to browse through when you want to customize a certain question or text field in general. I think it would be much more fun if you can use emojis. 

<img width="595" alt="Screenshot 2020-03-11 at 21 54 40" src="https://user-images.githubusercontent.com/50360982/76463033-03c21b00-63e3-11ea-89f0-b5d2603d2fb8.png">

What do you think?

**Comment by mik-laj** [comment]
Good idea. We can use https://github.com/missive/emoji-mart

**Comment by nuclearpinguin** [comment]
+1 for this idea! ✅

**Comment by antoinejaussoin** [comment]
Yeah that's not a bad idea at all, much more practical than icons.
The downside though is cross-platform: emojis are not displayed exactly the same across different envs, and some OS might not even have them. I'll investigate a bit more but I like the idea.

**Comment by mik-laj** [comment]
@antoinejaussoin It's cross platform.  Please look at [`set`](https://github.com/missive/emoji-mart#sheet-sizes) option.  If some emoji is not supported, you could set [unsupported emoji fallback](https://github.com/missive/emoji-mart#unsupported-emojis-fallback).

May God protect you from the coronavirus!

**Comment by antoinejaussoin** [comment]
It took a while but I've finally got around to do this. It will land in the next version, and is now available on the canary build.
